version: '3.1'


services:
  app:
    image: 'simple-docker-app:latest'
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simple_docker_app_db
    ports:
      - "5433:5432"

